workflows:
  ios_poc:
    name: iOS TryggSamtal PoC
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "TryggSamtal.xcodeproj"
        XCODE_SCHEME: "TryggSamtal"
        BUNDLE_ID: "com.yourname.tryggsamtal"
        TEAM_ID: "93397B64RG"
        PROVISIONING_PROFILE_NAME: "TryggsamtalDev"   # exact file name (without .mobileprovision)
    scripts:
      - name: Install tools
        script: |
          brew update || true
          brew install xcodegen || true

      - name: Generate Xcode project via XcodeGen
        script: |
          echo "PWD:" && pwd
          echo "List before:" && ls -la
          xcodegen generate --spec project.yml
          echo "List after:" && ls -la
          if [ ! -f "TryggSamtal.xcodeproj/project.pbxproj" ]; then
            echo "ERROR: XcodeGen failed to create TryggSamtal.xcodeproj"
            exit 1
          fi

      - name: Install local provisioning profile
        script: |
          echo ">>> Installing local .mobileprovision"
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          cp profiles/*.mobileprovision "$HOME/Library/MobileDevice/Provisioning Profiles/"
          echo ">>> Installed profiles:"
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles"

      - name: Build .ipa
        script: |
          cat > export_options.plist <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>development</string>
            <key>teamID</key><string>${TEAM_ID}</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${BUNDLE_ID}</key><string>${PROVISIONING_PROFILE_NAME}</string>
            </dict>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          PLIST

          echo ">>> Building with provisioning profile: ${PROVISIONING_PROFILE_NAME}"
          echo ">>> Listing installed profiles:"
          ls "$HOME/Library/MobileDevice/Provisioning Profiles"

          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/ios/TryggSamtal.xcarchive \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Development" \
            DEVELOPMENT_TEAM=${TEAM_ID} \
            PROVISIONING_PROFILE_SPECIFIER="${PROVISIONING_PROFILE_NAME}" \
            PRODUCT_BUNDLE_IDENTIFIER=${BUNDLE_ID}

          xcodebuild -exportArchive \
            -archivePath build/ios/TryggSamtal.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
