workflows:
  ios_poc:
    name: iOS TryggSamtal PoC
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: "com.yourname.tryggsamtal"
        TEAM_ID: "93397B64RG"
        XCODE_PROJECT: "TryggSamtal.xcodeproj"
        XCODE_SCHEME: "TryggSamtal"
        IPA_NAME: "TryggSamtal"
        CODE_SIGN_IDENTITY: "Apple Development: Dane Benjamen"

        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY

    scripts:
      - name: Install tools
        script: |
          brew update || true
          brew install xcodegen xcbeautify || true

      - name: Generate Xcode project via XcodeGen
        script: |
          echo "PWD:" && pwd
          ls -la
          xcodegen generate --spec project.yml
          ls -la
          if [ ! -f "TryggSamtal.xcodeproj/project.pbxproj" ]; then
            echo "ERROR: XcodeGen failed to create TryggSamtal.xcodeproj"
            exit 1
          fi

      - name: Set up keychain and add uploaded certificates
        script: |
          keychain initialize
          keychain add-certificates
          echo "✅ Certificates added successfully"

      - name: Install local provisioning profile
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profiles/TryggsamtalDev.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "✅ Provisioning profile installed"

      - name: Build .ipa (archive + export)
        script: |
          set -e
          echo ">>> Clean"
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" | xcbeautify

          echo ">>> Archive"
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/ios/TryggSamtal.xcarchive \
            CODE_SIGN_STYLE=Manual \
            "CODE_SIGN_IDENTITY=Apple Development" \
            DEVELOPMENT_TEAM=$TEAM_ID \
            PROVISIONING_PROFILE_SPECIFIER="Tryggsamtal-Dev" \
            PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID | xcbeautify

          echo ">>> Export .ipa"
          xcodebuild -exportArchive \
            -archivePath build/ios/TryggSamtal.xcarchive \
            -exportPath build/ios \
            -exportOptionsPlist export_options.plist | xcbeautify

      - name: Upload to TestFlight
        script: |
          echo ">>> Uploading to TestFlight..."
          app-store-connect publish \
            --path "build/ios/$IPA_NAME.ipa" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --release-type TESTFLIGHT \
            --submit-for-review false

    artifacts:
      - build/ios/**/*.ipa
      - build/ios/**/*.xcarchive
      - export_options.plist
