workflows:
  ios_poc:
    name: "iOS TryggSamtal PoC"
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "TryggSamtal.xcodeproj"
        XCODE_SCHEME: "TryggSamtal"
        IPA_NAME: "TryggSamtal"
        TEAM_ID: $TEAM_ID
        BUNDLE_ID: $BUNDLE_ID
        PROVISIONING_PROFILE_NAME: $PROVISIONING_PROFILE_NAME
    scripts:
      - name: Install dependencies
        script: |
          brew update || true
          brew install xcodegen xcbeautify || true

      - name: Generate Xcode project
        script: |
          echo "Generating Xcode project..."
          xcodegen generate --spec project.yml
          ls -la

      - name: Import certificate and provisioning profile
        script: |
          echo "Decoding and installing signing assets..."
          echo $CERT_P12_B64 | base64 --decode > ios_dev.p12
          security create-keychain -p "" build.keychain
          security import ios_dev.p12 -k ~/Library/Keychains/build.keychain -P "$CERT_P12_PASSWORD" -T /usr/bin/codesign
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profiles/TryggsamtalDev.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build .ipa (archive + export)
        script: |
          set -e
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" | xcbeautify
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/ios/"$IPA_NAME".xcarchive \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_NAME" \
            CODE_SIGN_STYLE=Manual | xcbeautify

          xcodebuild -exportArchive \
            -archivePath build/ios/"$IPA_NAME".xcarchive \
            -exportOptionsPlist export_options.plist \
            -exportPath build/ios/ipa | xcbeautify

      - name: Upload to TestFlight
        script: |
          app-store-connect publish \
            --path "build/ios/ipa/$IPA_NAME.ipa" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --testflight \
            --whats-new "Initial TryggSamtal build uploaded automatically via Codemagic CI/CD."

    artifacts:
      - build/ios/ipa/*.ipa
