workflows:
  ios_poc:
    name: "iOS TryggSamtal PoC"
    environment:
      xcode: latest
      groups:
        - admin
      vars:
        BUNDLE_ID: "com.yourname.tryggsamtal"
        TEAM_ID: "93397B64RG"
        XCODE_PROJECT: "TryggSamtal.xcodeproj"
        XCODE_SCHEME: "TryggSamtal"
        IPA_NAME: "TryggSamtal"
        CODESIGN_ID: "Apple Development"
        PROFILE_PATH: "profiles/TryggsamtalDev.mobileprovision"
        KEYCHAIN_PATH: "$HOME/Library/Keychains/build.keychain-db"

    scripts:
      - name: Install tools
        script: |
          brew update || true
          brew install xcodegen xcbeautify || true

      - name: Generate Xcode project via XcodeGen
        script: |
          echo "PWD:" && pwd
          ls -la
          if [ -f project.yml ]; then
            xcodegen generate
          else
            echo "❌ Missing project.yml file"; exit 1
          fi
          test -f "TryggSamtal.xcodeproj/project.pbxproj" || { echo "❌ XcodeGen failed"; exit 1; }

      - name: Diagnose p12 env payload
        script: |
          set -e
          echo ">>> Validating CERT_P12_B64 and CERT_P12_PASSWORD..."
          if [ -z "$CERT_P12_B64" ] || [ -z "$CERT_P12_PASSWORD" ]; then
            echo "❌ Missing CERT_P12_B64 or CERT_P12_PASSWORD"; exit 1
          fi
          echo "$CERT_P12_B64" | base64 --decode > check.p12
          echo ">>> File type:" && file check.p12 || true
          echo ">>> Trying to open .p12 with provided password..."
          if ! (openssl pkcs12 -in check.p12 -nokeys -passin pass:"$CERT_P12_PASSWORD" -info -clcerts >/dev/null 2>&1); then
            echo "❌ OpenSSL could not read the PKCS#12 with the given password (wrong password or corrupted p12)"
            exit 1
          fi
          echo "✅ OpenSSL verified the PKCS#12 successfully"

      - name: Create and configure keychain (no partition-list yet)
        script: |
          set -e
          echo ">>> Creating keychain at $KEYCHAIN_PATH"
          security create-keychain -p "" "$KEYCHAIN_PATH"
          # Make it the only user keychain to avoid ambiguity
          security list-keychains -d user -s "$KEYCHAIN_PATH"
          security default-keychain -s "$KEYCHAIN_PATH"
          security unlock-keychain -p "" "$KEYCHAIN_PATH"
          echo "✅ Keychain created & set as default"

      - name: Inject Apple Development .p12 into keychain (robust)
        script: |
          set -e
          echo ">>> Importing Apple Development certificate (with legacy repack fallback)..."
          echo "$CERT_P12_B64" | base64 --decode > ios_dev.p12

          # Try direct import first
          if security import ios_dev.p12 \
              -k "$KEYCHAIN_PATH" \
              -P "$CERT_P12_PASSWORD" \
              -T /usr/bin/codesign -T /usr/bin/security; then
            echo "✅ Direct security import succeeded"
          else
            echo "⚠️ Direct import failed; attempting legacy repack using OpenSSL..."
           
