workflows:
  ios_poc:
    name: iOS TryggSamtal PoC
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "TryggSamtal.xcodeproj"
        XCODE_SCHEME: "TryggSamtal"
        BUNDLE_ID: "com.yourname.tryggsamtal"   # byt till samma som i project.yml
    scripts:
      - name: Install tools
        script: |
          brew update || true
          brew install xcodegen || true

      - name: Fetch whisper.cpp
        script: |
          mkdir -p vendor
          if [ ! -d vendor/whisper.cpp ]; then
            git clone --depth 1 https://github.com/ggerganov/whisper.cpp.git vendor/whisper.cpp
          fi

      - name: Add Whisper model
        script: |
          mkdir -p Resources/Models
          if [ ! -f Resources/Models/ggml-base.bin ]; then
            curl -L -o Resources/Models/ggml-base.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin
          fi

      - name: Generate Xcode project via XcodeGen
        script: |
          xcodegen generate
          ls -la

      # Automatisk signering via din Apple-integration
      - name: Fetch signing files from App Store Connect
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_DEVELOPMENT --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"

      - name: Set up keychain and use profiles
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Build .ipa
        script: |
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - $XCODE_PROJECT

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true

