workflows:
  ios-release:
    name: "iOS Release – TestFlight Upload"
    environment:
      vars:
        APP_NAME: "TryggSamtal"
        BUNDLE_ID: "com.yourname.tryggsamtal"
        APPLE_TEAM_ID: "93397B64RG"
        APP_STORE_CONNECT_USERNAME: "his_81@hotmail.com"
        APP_STORE_CONNECT_PASSWORD: Encrypted(Your_App_Specific_Password)
        CERTIFICATE_PASSWORD: "1234Benjamen"
      xcode: latest
    scripts:
      - name: Preflight – verify provisioning profiles
        script: |
          echo "🔍 Checking profiles..."
          ls -l profiles/
          security cms -D -i profiles/TryggsamtalDist.mobileprovision | grep -A2 '<key>Name</key>'
      
      - name: Decode and import Distribution certificate
        script: |
          echo "🔑 Importing iOS Distribution certificate..."
          echo "$DIST_P12_BASE64" | base64 --decode > ios_dist.p12
          security create-keychain -p "" build.keychain
          security import ios_dist.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -A
          security set-keychain-settings -lut 21600 build.keychain
          security unlock-keychain -p "" build.keychain
          security list-keychains -s build.keychain

      - name: Install provisioning profile
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profiles/TryggsamtalDist.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "✅ Distribution provisioning profile installed"

      - name: Validate & fix IPA Info.plist casing (if needed)
        script: |
          unzip -l build/ios/ipa/TryggSamtal.ipa | grep -i Info.plist || true
          unzip -o build/ios/ipa/TryggSamtal.ipa -d temp_ipa/
          if [ -f temp_ipa/Payload/TryggSamtal.app/info.plist ]; then
            mv temp_ipa/Payload/TryggSamtal.app/info.plist temp_ipa/Payload/TryggSamtal.app/Info.plist
            cd temp_ipa && zip -qry ../build/ios/ipa/TryggSamtal.fixed.ipa .
            cd ..
            echo "✅ Rebuilt IPA with proper Info.plist casing"
          else
            echo "ℹ️ Info.plist already correct"
          fi

      - name: Upload to TestFlight (Apple ID + app-specific password)
        script: |
          echo "📤 Uploading to TestFlight..."
          xcrun altool --upload-app \
            --file build/ios/ipa/TryggSamtal.fixed.ipa \
            --type ios \
            --username "$APP_STORE_CONNECT_USERNAME" \
            --password "$APP_STORE_CONNECT_PASSWORD" \
            --output-format json

    artifacts:
      - build/ios/ipa/*.ipa
