workflows:
  ios_poc:
    name: iOS TryggSamtal PoC
    environment:
      xcode: latest
      vars:
        # ----- BYT DESSA TRE -----
        BUNDLE_ID: "com.yourname.tryggsamtal"   # exakt samma som i din profil
        TEAM_ID: "93397B64RG"                   # ditt Apple Team ID
        XCODE_SCHEME: "TryggSamtal"
        XCODE_PROJECT: "TryggSamtal.xcodeproj"
        # --------------------------

        # Public bundle name (används bara till filnamn)
        IPA_NAME: "TryggSamtal"

      # Lägg INTE in dina App Store Connect-hemligheter i git.
      # Sätt dem som Secure env vars i Codemagic UI:
      # APP_STORE_CONNECT_ISSUER_ID
      # APP_STORE_CONNECT_KEY_IDENTIFIER
      # APP_STORE_CONNECT_PRIVATE_KEY
      # (valfritt) TESTFLIGHT_RELEASE_NOTES

    scripts:
      - name: Install tools
        script: |
          brew update || true
          brew install xcodegen xcbeautify || true

      - name: Generate Xcode project via XcodeGen
        script: |
          echo "PWD:" && pwd
          ls -la
          xcodegen generate --spec project.yml
          test -f "TryggSamtal.xcodeproj/project.pbxproj" || { echo "XcodeGen misslyckades"; exit 1; }

      - name: Install local provisioning profile (from repo/profiles/)
        script: |
          set -e
          echo ">>> Installing .mobileprovision from profiles/"
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"

          PROFILE_PATH=$(ls profiles/*.mobileprovision 2>/dev/null | head -n 1)
          if [ -z "$PROFILE_PATH" ]; then
            echo "Hittar ingen .mobileprovision i ./profiles"; exit 1
          fi
          echo "Found profile: $PROFILE_PATH"

          # Extrahera UUID ur binär mobileprovision (robust metod)
          UUID=$(security cms -D -i "$PROFILE_PATH" | plutil -extract UUID raw -)
          if [ -z "$UUID" ]; then
            echo "Kunde inte läsa ut UUID ur $PROFILE_PATH"; security cms -D -i "$PROFILE_PATH" | head -n 40; exit 1
          fi
          echo "Extracted UUID: $UUID"

          cp "$PROFILE_PATH" "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.mobileprovision"

          # Exportera till env för senare steg
          echo "PROVISIONING_PROFILE_UUID=$UUID" >> $CM_ENV

          echo ">>> Installed profiles:"
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles"

      - name: Build .ipa (archive + export)
        script: |
          set -e
          test -n "$PROVISIONING_PROFILE_UUID" || { echo "Saknar PROVISIONING_PROFILE_UUID"; exit 1; }

          cat > export_options.plist <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>development</string>
            <key>teamID</key><string>${TEAM_ID}</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${BUNDLE_ID}</key><string>${PROVISIONING_PROFILE_UUID}</string>
            </dict>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          PLIST

          echo ">>> Clean"
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" | xcbeautify

          echo ">>> Archive"
          set -o pipefail
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "build/ios/${IPA_NAME}.xcarchive" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Development" \
            DEVELOPMENT_TEAM="${TEAM_ID}" \
            PRODUCT_BUNDLE_IDENTIFIER="${BUNDLE_ID}" \
            PROVISIONING_PROFILE_SPECIFIER="${PROVISIONING_PROFILE_UUID}" \
            | tee xcodebuild_archive.log | xcbeautify
          echo "Archive done."

          echo ">>> Export IPA"
          xcodebuild -exportArchive \
            -archivePath "build/ios/${IPA_NAME}.xcarchive" \
            -exportOptionsPlist export_options.plist \
            -exportPath build/ios/ipa \
            | xcbeautify

      - name: Publish to TestFlight
        script: |
          set -e
          IPA="$(ls build/ios/ipa/*.ipa | head -n 1)"
          test -f "$IPA" || { echo "Saknar IPA att ladda upp"; exit 1; }

          # Sanity-check av ASC-hemligheter
          for v in APP_STORE_CONNECT_ISSUER_ID APP_STORE_CONNECT_KEY_IDENTIFIER APP_STORE_CONNECT_PRIVATE_KEY; do
            if [ -z "${!v}" ]; then
              echo "Env var $v saknas. Sätt den som Secure var i Codemagic UI (Workflow settings → Environment variables)."; exit 1
            fi
          done

          echo ">>> Uploading $IPA to TestFlight"
          # 'publish' läser bundle id/app från IPA automatiskt om appen redan finns i App Store Connect
          app-store-connect publish \
            --path "$IPA" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --submit-for-beta-review \
            --release-notes "${TESTFLIGHT_RELEASE_NOTES:-Automatisk build via Codemagic}"

          echo "Upload queued on App Store Connect."

    artifacts:
      - build/ios/ipa/*.ipa
