workflows:
  ios_poc:
    name: iOS TryggSamtal PoC
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "TryggSamtal.xcodeproj"
        XCODE_SCHEME: "TryggSamtal"
        BUNDLE_ID: "com.yourname.tryggsamtal"        # <-- BYT
        TEAM_ID: "93397B64RG"                        # <-- BYT
        PROVISIONING_PROFILE_NAME: "com.yourname.tryggsamtl.com" # <-- BYT
    scripts:
      - name: Install tools
        script: |
          brew update || true
          brew install xcodegen || true

      - name: Generate Xcode project via XcodeGen
        script: |
          echo "PWD:" && pwd
          echo "List before:" && ls -la
          xcodegen generate --spec project.yml
          echo "List after:" && ls -la
          if [ ! -f "TryggSamtal.xcodeproj/project.pbxproj" ]; then
            echo "ERROR: XcodeGen failed to create TryggSamtal.xcodeproj"
            exit 1
          fi

      # Installerar dina uppladdade .p12/.mobileprovision i keychain och kopplar dem till projektet
      - name: Set up keychain and use uploaded profiles
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      # Skapar giltig XML-plist för export
- name: Build .ipa
  script: |
    # Skapa exportOptions (XML)
    cat > export_options.plist <<PLIST
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
      <key>method</key><string>development</string>
      <key>teamID</key><string>${TEAM_ID}</string>
      <key>signingStyle</key><string>manual</string>
      <key>provisioningProfiles</key>
      <dict>
        <key>${BUNDLE_ID}</key><string>${PROVISIONING_PROFILE_NAME}</string>
      </dict>
      <key>compileBitcode</key><false/>
    </dict>
    </plist>
    PLIST

    echo ">>> List schemes & targets"
    xcodebuild -list -project "$XCODE_PROJECT" | sed -n '1,120p'

    echo ">>> Show key build settings"
    xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -showBuildSettings | egrep 'PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|PROVISIONING_PROFILE_SPECIFIER|CODE_SIGN_STYLE|CODE_SIGN_IDENTITY' || true

    echo ">>> Clean"
    xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME"

    echo ">>> Archive (full log)"
    set -o pipefail
    xcodebuild archive \
      -project "$XCODE_PROJECT" \
      -scheme "$XCODE_SCHEME" \
      -archivePath build/ios/TryggSamtal.xcarchive \
      CODE_SIGN_STYLE=Manual \
      CODE_SIGN_IDENTITY="Apple Development" \
      DEVELOPMENT_TEAM=$TEAM_ID \
      PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_NAME" \
      PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
      | tee xcodebuild_archive.log | xcpretty

    ARCHIVE_STATUS=$?
    if [ $ARCHIVE_STATUS -ne 0 ]; then
      echo ">>> xcodebuild archive failed (status $ARCHIVE_STATUS). Showing last 200 lines:"
      tail -n 200 xcodebuild_archive.log
      exit $ARCHIVE_STATUS
    fi

    echo ">>> Export IPA"
    xcodebuild -exportArchive \
      -archivePath build/ios/TryggSamtal.xcarchive \
      -exportOptionsPlist export_options.plist \
      -exportPath build/ios/ipa \
      | tee xcodebuild_export.log | xcpretty || { echo 'Export failed'; tail -n 200 xcodebuild_export.log; exit 1; }


    artifacts:
      - build/ios/ipa/*.ipa
