workflows:
  ios_poc:
    name: iOS TryggSamtal PoC
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: "com.yourname.tryggsamtal"
        TEAM_ID: "93397B64RG"
        XCODE_PROJECT: "TryggSamtal.xcodeproj"
        XCODE_SCHEME: "TryggSamtal"
        IPA_NAME: "TryggSamtal"
        CODESIGN_ID: "Apple Development: Dane Benjamen"
        PROVISIONING_PROFILE_NAME: "Tryggsamtal-Dev"

        # Dessa lägger du som Secure Environment variables i Codemagic UI
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(ISSUER_ID)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(KEY_ID)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(PRIVATE_KEY)
        TESTFLIGHT_RELEASE_NOTES: "Initial build uploaded from Codemagic"

    scripts:
      - name: Install tools
        script: |
          brew update || true
          brew install xcodegen xcbeautify || true

      - name: Generate Xcode project via XcodeGen
        script: |
          echo "PWD:" && pwd
          ls -la
          xcodegen generate --spec project.yml
          echo "Generated Xcode project:"
          ls -la TryggSamtal.xcodeproj || { echo "❌ Missing .xcodeproj"; exit 1; }

      - name: Set up keychain and add uploaded certificates
        script: |
          keychain initialize
          keychain add-certificates
          echo "✅ Certificates added successfully"

      - name: Install provisioning profile
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_PATH=$(find $CM_BUILD_DIR -name "*.mobileprovision" | head -1)
          if [ -z "$PROFILE_PATH" ]; then
            echo "❌ No provisioning profile found"
            exit 1
          fi
          echo "Found provisioning profile at: $PROFILE_PATH"
          cp "$PROFILE_PATH" ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "✅ Provisioning profile installed"

      - name: Debug list code signing identities
        script: |
          security find-identity -v -p codesigning
          ls ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build .ipa (archive + export)
        script: |
          set -e
          echo ">>> Clean"
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" | xcbeautify
          echo ">>> Archive"
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/ios/"$IPA_NAME".xcarchive \
            CODE_SIGN_IDENTITY="$CODESIGN_ID" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_NAME" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            CODE_SIGN_STYLE=Manual | xcbeautify

          echo ">>> Export IPA"
          mkdir -p build/ios/ipa
          xcodebuild -exportArchive \
            -archivePath build/ios/"$IPA_NAME".xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist export_options.plist | xcbeautify

      - name: Upload to TestFlight
        script: |
          echo ">>> Uploading to TestFlight..."
          app-store-connect upload \
            --api-key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --api-issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --path "build/ios/ipa/${IPA_NAME}.ipa" \
            --release-notes "$TESTFLIGHT_RELEASE_NOTES"
          echo "✅ Uploaded successfully to TestFlight"

    artifacts:
      - build/ios/ipa/*.ipa
