workflows:
  ios_poc:
    name: "iOS TryggSamtal PoC"
    environment:
      xcode: latest
      groups:
        - admin
      vars:
        BUNDLE_ID: "com.yourname.tryggsamtal"
        TEAM_ID: "93397B64RG"
        XCODE_PROJECT: "TryggSamtal.xcodeproj"
        XCODE_SCHEME: "TryggSamtal"
        IPA_NAME: "TryggSamtal"
        CODESIGN_ID: "Apple Development"    # håll generiskt
        PROFILE_PATH: "profiles/TryggsamtalDev.mobileprovision"
        KEYCHAIN_PATH: "$HOME/Library/Keychains/build.keychain-db"

    scripts:
      - name: Install tools
        script: |
          brew update || true
          brew install xcodegen xcbeautify openssl || true

      - name: Generate Xcode project via XcodeGen
        script: |
          echo "PWD:" && pwd
          ls -la
          if [ -f project.yml ]; then
            xcodegen generate
          else
            echo "❌ Missing project.yml file"; exit 1
          fi
          test -f "TryggSamtal.xcodeproj/project.pbxproj" || { echo "❌ XcodeGen failed"; exit 1; }

      - name: Diagnose p12 env payload
        script: |
          set -e
          echo ">>> Validating CERT_P12_B64 and CERT_P12_PASSWORD..."
          if [ -z "$CERT_P12_B64" ] || [ -z "$CERT_P12_PASSWORD" ]; then
            echo "❌ Missing CERT_P12_B64 or CERT_P12_PASSWORD"; exit 1
          fi
          echo "$CERT_P12_B64" | base64 --decode > check.p12
          echo ">>> File type:" && file check.p12 || true
          echo ">>> Trying to open .p12 with provided password..."
          if ! (openssl pkcs12 -in check.p12 -nokeys -passin pass:"$CERT_P12_PASSWORD" -info -clcerts >/dev/null 2>&1); then
            echo "❌ OpenSSL could not read the PKCS#12 with the given password (wrong password or corrupted p12)"
            exit 1
          fi
          echo "✅ OpenSSL verified the PKCS#12 successfully"

      - name: Create and configure keychain (no partition-list yet)
        script: |
          set -e
          echo ">>> Creating keychain at $KEYCHAIN_PATH"
          security create-keychain -p "" "$KEYCHAIN_PATH"
          security list-keychains -d user -s "$KEYCHAIN_PATH"
          security default-keychain -s "$KEYCHAIN_PATH"
          security unlock-keychain -p "" "$KEYCHAIN_PATH"
          echo "✅ Keychain created & set as default"

      - name: Inject Apple Development .p12 into keychain (robust, no heredocs)
        script: |
          set -e
          echo ">>> Importing Apple Development certificate..."
          echo "$CERT_P12_B64" | base64 --decode > ios_dev.p12

          # Försök direkt import av .p12
          if security import ios_dev.p12 -k "$KEYCHAIN_PATH" -P "$CERT_P12_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security; then
            echo "✅ Direct security import succeeded"
          else
            echo "⚠️ Direct import failed; extracting cert+key PEM and importing separately..."
            # Extrahera cert + privat nyckel
            openssl pkcs12 -in ios_dev.p12 -passin pass:"$CERT_P12_PASSWORD" -nodes -clcerts -out extracted.pem

            # Skriv cert
            awk 'BEGIN{p=0} /BEGIN CERTIFICATE/{p=1} p{print} /END CERTIFICATE/{p=0}' extracted.pem > dev_cert.pem
            # Skriv key
            awk 'BEGIN{p=0} /BEGIN PRIVATE KEY/{p=1} p{print} /END PRIVATE KEY/{p=0}' extracted.pem > dev_key.pem

            # Importera cert och nyckel separat
            security import dev_cert.pem -k "$KEYCHAIN_PATH" -T /usr/bin/codesign -T /usr/bin/security
            security import dev_key.pem  -k "$KEYCHAIN_PATH" -P "" -A -t private -f pem || \
            security import dev_key.pem  -k "$KEYCHAIN_PATH" -P "" -A -T /usr/bin/codesign -T /usr/bin/security

            rm -f extracted.pem dev_cert.pem dev_key.pem
            echo "✅ Imported certificate and private key separately"
          fi

          echo ">>> Codesigning identities in keychain (pre-partition-list):"
          security find-identity -v -p codesigning "$KEYCHAIN_PATH" || true
          if ! security find-identity -v -p codesigning "$KEYCHAIN_PATH" | grep -F "Apple Development" >/dev/null; then
            echo "❌ No 'Apple Development' identity found after import."; exit 1
          fi

          echo ">>> Setting key partition list…"
          security set-key-partition-list -S apple-tool:,apple: -s -k "" "$KEYCHAIN_PATH"
          echo "✅ Key partition list set"

      - name: Install provisioning profile (extract UUID)
        script: |
          set -e
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          if [ ! -f "$PROFILE_PATH" ]; then
            echo "❌ Provisioning profile not found at $PROFILE_PATH"; exit 1
          fi
          echo "Found profile: $PROFILE_PATH"
          PLIST=$(security cms -D -i "$PROFILE_PATH")
          UUID=$(echo "$PLIST" | plutil -extract UUID raw -)
          NAME=$(echo "$PLIST" | plutil -extract Name raw - 2>/dev/null || true)
          APPID=$(echo "$PLIST" | plutil -extract Entitlements.application-identifier raw - 2>/dev/null || true)
          if [ -z "$UUID" ]; then
            echo "❌ Could not extract UUID"; echo "$PLIST" | head -n 40; exit 1
          fi
          echo "Profile Name: ${NAME:-<unknown>}"
          echo "Profile UUID: $UUID"
          echo "application-identifier: ${APPID:-<unknown>} (expected ${TEAM_ID}.${BUNDLE_ID})"
          cp "$PROFILE_PATH" "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.mobileprovision"
          echo "PROVISIONING_PROFILE_UUID=$UUID" >> $CM_ENV
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles"

      - name: Build .ipa (archive + export)
        script: |
          set -e
          test -n "$PROVISIONING_PROFILE_UUID" || { echo "❌ Missing PROVISIONING_PROFILE_UUID"; exit 1; }

          echo ">>> Clean"
          xcodebuild clean \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' | xcbeautify

          echo ">>> Show key build settings (pre-archive)"
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -showBuildSettings | egrep 'PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|CODE_SIGN_STYLE|CODE_SIGN_IDENTITY|PROVISIONING_PROFILE_SPECIFIER' || true

          echo ">>> Archive"
          set -o pipefail
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath "build/ios/${IPA_NAME}.xcarchive" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="${CODESIGN_ID}" \
            DEVELOPMENT_TEAM="${TEAM_ID}" \
            PRODUCT_BUNDLE_IDENTIFIER="${BUNDLE_ID}" \
            PROVISIONING_PROFILE_SPECIFIER="${PROVISIONING_PROFILE_UUID}" \
            | tee xcodebuild_archive.log | xcbeautify

          STATUS=$?
          if [ $STATUS -ne 0 ]; then
            echo ">>> Archive failed (status $STATUS). Last 150 lines:"
            tail -n 150 xcodebuild_archive.log
            exit $STATUS
          fi

          echo ">>> Write export options to file"
          cat > export_options.plist <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>development</string>
            <key>teamID</key><string>${TEAM_ID}</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${BUNDLE_ID}</key><string>${PROVISIONING_PROFILE_UUID}</string>
            </dict>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          PLIST

          echo ">>> Export IPA"
          xcodebuild -exportArchive \
            -archivePath "build/ios/${IPA_NAME}.xcarchive" \
            -exportOptionsPlist export_options.plist \
            -exportPath build/ios/ipa \
            | xcbeautify

          echo "IPA(s) created:"
          ls -la build/ios/ipa || true

      # === NYTT 1/2: Validera & fixa Info.plist-casing i IPA ===
      - name: Validate & fix IPA Info.plist casing (if needed)
        script: |
          set -e
          IPA_ORIG="build/ios/ipa/${IPA_NAME}.ipa"
          test -f "$IPA_ORIG" || { echo "❌ IPA saknas: $IPA_ORIG"; exit 1; }

          echo ">>> Inspect original IPA:"
          unzip -l "$IPA_ORIG" | sed -n '1,120p'

          if unzip -l "$IPA_ORIG" | grep -q "Payload/.*/info.plist"; then
            echo "⚠️ Found lowercase info.plist, rebuilding IPA with proper casing…"
            WORK="$(mktemp -d)"
            pushd "$WORK" >/dev/null
            unzip -q "$OLDPWD/$IPA_ORIG"
            APPDIR="$(ls -d Payload/*.app)"
            if [ -f "$APPDIR/info.plist" ]; then
              mv "$APPDIR/info.plist" "$APPDIR/Info.plist"
            fi
            mkdir -p "$OLDPWD/build/ios/ipa"
            OUT="$OLDPWD/build/ios/ipa/${IPA_NAME}.fixed.ipa"
            zip -qry "$OUT" Payload
            popd >/dev/null
            rm -rf "$WORK"
            echo "✅ Repacked IPA: $OUT"
            echo "IPA_UPLOAD_PATH=$OUT" >> $CM_ENV
          else
            echo "✅ Info.plist casing OK"
            echo "IPA_UPLOAD_PATH=$IPA_ORIG" >> $CM_ENV
          fi

      # === NYTT 2/2: Preflight – verifiera App Store Connect API-nyckeln ===
      - name: preflight: verify app store connect api access
        script: |
          set -e
          for v in APP_STORE_CONNECT_ISSUER_ID APP_STORE_CONNECT_KEY_IDENTIFIER APP_STORE_CONNECT_PRIVATE_KEY; do
            test -n "${!v}" || { echo "❌ Missing $v"; exit 1; }
          done

          # Normalisera .p8 från env → appstore_key.p8
          printf "%s" "$APP_STORE_CONNECT_PRIVATE_KEY" > appstore_key.raw
          tr -d '\r' < appstore_key.raw > appstore_key.nocr
          sed -e '1s/^"//' -e '$s/"$//' appstore_key.nocr > appstore_key.stripped
          if grep -q '\\n' appstore_key.stripped; then
            printf "%b" "$(cat appstore_key.stripped)" > appstore_key.p8
          else
            cp appstore_key.stripped appstore_key.p8
          fi
          chmod 600 appstore_key.p8
          head -n 1 appstore_key.p8; tail -n 1 appstore_key.p8

          # Enkel ping mot API: lista appar (ingen känslig output)
          app-store-connect apps \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key appstore_key.p8 --json >/dev/null

          echo "✅ App Store Connect API key ok"

      - name: Upload to TestFlight (pass PEM content, minimal flags)
        script: |
          set -e
          test -n "$IPA_UPLOAD_PATH" || IPA_UPLOAD_PATH="build/ios/ipa/${IPA_NAME}.ipa"
          echo ">>> Uploading to TestFlight"
          app-store-connect publish \
            --path "$IPA_UPLOAD_PATH" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key appstore_key.p8 \
            --platform IOS \
            --testflight \
            --verbose
          echo "✅ Upload queued."

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/*.xcarchive
      - export_options.plist
