workflows:
  ios_poc:
    name: iOS TryggSamtal PoC
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "TryggSamtal.xcodeproj"
        XCODE_SCHEME: "TryggSamtal"
        BUNDLE_ID: "com.yourname.tryggsamtal"        # <-- BYT
        TEAM_ID: "93397B64RG"                        # <-- BYT
        PROVISIONING_PROFILE_NAME: "Tryggsamtal_provision" # <-- BYT
    scripts:
      - name: Install tools
        script: |
          brew update || true
          brew install xcodegen || true

      - name: Generate Xcode project via XcodeGen
        script: |
          echo "PWD:" && pwd
          echo "List before:" && ls -la
          xcodegen generate --spec project.yml
          echo "List after:" && ls -la
          if [ ! -f "TryggSamtal.xcodeproj/project.pbxproj" ]; then
            echo "ERROR: XcodeGen failed to create TryggSamtal.xcodeproj"
            exit 1
          fi

      # Installerar dina uppladdade .p12/.mobileprovision i keychain och kopplar dem till projektet
      - name: Set up keychain and use uploaded profiles
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      # Skapar giltig XML-plist för export
      - name: Build .ipa
        script: |
          cat > export_options.plist <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>development</string>
            <key>teamID</key><string>${TEAM_ID}</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${BUNDLE_ID}</key><string>${PROVISIONING_PROFILE_NAME}</string>
            </dict>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          PLIST

          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
