workflows:
  ios_release:
    name: "TryggSamtal Release"

    integrations:
      app_store_connect: codemagic  # your existing integration

    environment:
      xcode: latest

    scripts:
      - name: Generate Xcode project
        script: |
          set -e
          cd "$CM_BUILD_DIR"

          echo "Top-level contents:"
          ls
          echo

          if [ ! -f "project.yml" ]; then
            echo "❌ project.yml not found in $CM_BUILD_DIR"
            exit 1
          fi

          # Install XcodeGen if needed
          if ! command -v xcodegen >/dev/null 2>&1; then
            echo "Installing XcodeGen via Homebrew..."
            brew install xcodegen
          fi

          echo "Generating Xcode project with XcodeGen..."
          xcodegen generate

          echo "Contents after xcodegen:"
          ls
          echo

      - name: Build IPA (automatic signing)
        script: |
          set -e
          cd "$CM_BUILD_DIR"

          PROJECT="$CM_BUILD_DIR/TryggSamtal.xcodeproj"
          SCHEME="TryggSamtal"

          if [ ! -d "$PROJECT" ]; then
            echo "❌ Project not found at $PROJECT"
            ls
            exit 1
          fi

          echo "Using project: $PROJECT"
          echo "Using scheme: $SCHEME"
          echo "Building IPA with xcode-project (automatic signing via Codemagic)..."

          xcode-project build-ipa \
            --project "$PROJECT" \
            --scheme "$SCHEME"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: true
        submit_to_app_store: false
