workflows:
  ios_release:
    name: "TryggSamtal Release"

    integrations:
      app_store_connect: codemagic   # your App Store Connect API key integration

    environment:
      xcode: latest

      # 👇 This is the key part from the "Signing iOS apps" docs
      ios_signing:
        # Option 1: reference specific cert & profile that you uploaded
        provisioning_profiles:
          - tryggsamtal_dist_profile      # <- reference name from UI
        certificates:
          - tryggsamtal_dist_cert         # <- reference name from UI

        # (Do NOT set distribution_type / bundle_identifier when using references)

    scripts:
      # 1) Generate Xcode project using XcodeGen
      - name: Generate Xcode project
        script: |
          set -e
          cd "$CM_BUILD_DIR"

          echo "Top-level contents:"
          ls
          echo

          if [ ! -f "project.yml" ]; then
            echo "❌ project.yml not found in $CM_BUILD_DIR"
            exit 1
          fi

          if ! command -v xcodegen >/dev/null 2>&1; then
            echo "Installing XcodeGen via Homebrew..."
            brew install xcodegen
          fi

          echo "Generating Xcode project with XcodeGen..."
          xcodegen generate

          echo "Contents after xcodegen:"
          ls
          echo

      # 2) Apply provisioning profiles to the Xcode project (docs: xcode-project use-profiles)
      - name: Set up code signing on Xcode project
        script: |
          set -e
          cd "$CM_BUILD_DIR"

          PROJECT="$CM_BUILD_DIR/TryggSamtal.xcodeproj"

          if [ ! -d "$PROJECT" ]; then
            echo "❌ Project not found at $PROJECT"
            ls
            exit 1
          fi

          echo "Applying provisioning profiles with xcode-project use-profiles..."
          xcode-project use-profiles \
            --project "$PROJECT"

          echo "Expecting export_options.plist at \$HOME/export_options.plist after use-profiles."

      # 3) Build IPA using the export_options.plist generated by use-profiles
      - name: Build IPA
        script: |
          set -e
          cd "$CM_BUILD_DIR"

          PROJECT="$CM_BUILD_DIR/TryggSamtal.xcodeproj"
          SCHEME="TryggSamtal"
          EXPORT_PLIST="$HOME/export_options.plist"

          if [ ! -f "$EXPORT_PLIST" ]; then
            echo "❌ export_options.plist not found at $EXPORT_PLIST"
            ls "$HOME"
            exit 1
          fi

          echo "Using project: $PROJECT"
          echo "Using scheme: $SCHEME"
          echo "Using export options: $EXPORT_PLIST"

          xcode-project build-ipa \
            --project "$PROJECT" \
            --scheme "$SCHEME" \
            --export-options-plist "$EXPORT_PLIST"

    publishing:
      app_store_connect:
        auth: integration

        submit_to_testflight: true
        expire_build_submitted_for_review: true

        # optional beta groups if you have them set up in App Store Connect:
        # beta_groups:
        #   - Internal Testers

        submit_to_app_store: false
