workflows:
  ios_release:
    name: "TryggSamtal Release"

    # ---- App Store Connect integration ----
    integrations:
      app_store_connect: codemagic   # <-- your integration name

    environment:
      xcode: latest
      groups:
        - admin   # DIST_P12_BASE64 and DIST_P12_PASSWORD live here

    scripts:
      # ---- p12: decode + verify (already working) ----
      - name: Normalize & verify DIST_P12_BASE64
        script: |
          set -e
          echo "== ENV DIAGNOSTICS =="
          echo "DIST_P12_BASE64 length: ${#DIST_P12_BASE64}"
          echo "DIST_P12_BASE64 first 60 chars: ${DIST_P12_BASE64:0:60}"
          echo ""

          if [ -z "$DIST_P12_BASE64" ]; then
            echo "❌ DIST_P12_BASE64 is EMPTY in this workflow."
            exit 1
          fi

          echo "Normalizing p12 Base64..."
          printf "%s" "$DIST_P12_BASE64" > dist_p12.raw.txt

          python3 - << 'PYCODE'
          import base64, re, sys, pathlib

          raw_path = pathlib.Path('dist_p12.raw.txt')
          raw = raw_path.read_text()
          print("Raw file length:", len(raw))

          raw = raw.strip().strip('"').strip("'")
          print("After strip/quotes length:", len(raw))

          raw = re.sub(r'^data:[^,]+,', '', raw)
          print("After data: URL removal length:", len(raw))

          raw = raw.replace('\n','').replace('\r','')
          raw = re.sub(r'\s+','', raw)
          print("After whitespace removal length:", len(raw))

          raw = raw.replace('-', '+').replace('_', '/')
          raw += '=' * (-len(raw) % 4)

          if not raw:
            print('❌ Raw Base64 is empty after normalization.')
            sys.exit(1)

          try:
            decoded = base64.b64decode(raw)
          except Exception as e:
            print('❌ Decode failed:', e)
            sys.exit(1)

          print("Decoded bytes length:", len(decoded))
          if not decoded:
            print('❌ Decoded p12 is EMPTY (0 bytes). Check DIST_P12_BASE64 value.')
            sys.exit(1)

          with open('ios_dist.p12','wb') as f:
            f.write(decoded)
          print('✅ Base64 OK, bytes:', len(decoded))
          PYCODE

          openssl pkcs12 -in ios_dist.p12 -nokeys -passin pass:"$DIST_P12_PASSWORD" -info -clcerts >/dev/null 2>&1 \
            || { echo '❌ Invalid password or corrupted p12'; exit 1; }
          echo "✅ PKCS#12 verified"

      # ---- Build IPA: find workspace/project & scheme, then build ----
      - name: Build IPA
        script: |
          set -e
          echo "Looking for Xcode workspace/project under $CM_BUILD_DIR ..."
          echo "Top-level contents of repo:"
          ls "$CM_BUILD_DIR"
          echo

          WORKSPACE=$(find "$CM_BUILD_DIR" -name "*.xcworkspace" -not -path "*/Pods/*" | head -n1 || true)
          PROJECT=$(find "$CM_BUILD_DIR" -name "*.xcodeproj" -not -path "*/Pods/*" | head -n1 || true)

          echo "Detected workspace: $WORKSPACE"
          echo "Detected project:   $PROJECT"
          echo

          if [ -n "$WORKSPACE" ]; then
            echo "✅ Using workspace: $WORKSPACE"
            echo "Detecting scheme from workspace..."
            SCHEME=$(xcodebuild -list -workspace "$WORKSPACE" 2>/dev/null \
              | sed -n '/Schemes:/,/^$/p' \
              | sed '1d' \
              | sed '/^$/d' \
              | head -n1 \
              | sed 's/^[[:space:]]*//')
            if [ -z "$SCHEME" ]; then
              echo "❌ Could not detect a scheme from workspace."
              exit 1
            fi
            echo "Using scheme: $SCHEME"
            xcode-project build-ipa \
              --workspace "$WORKSPACE" \
              --scheme "$SCHEME" \
              --archive-flags "-destination 'generic/platform=iOS'"
          elif [ -n "$PROJECT" ]; then
            echo "✅ Using project: $PROJECT"
            echo "Detecting scheme from project..."
            SCHEME=$(xcodebuild -list -project "$PROJECT" 2>/dev/null \
              | sed -n '/Schemes:/,/^$/p' \
              | sed '1d' \
              | sed '/^$/d' \
              | head -n1 \
              | sed 's/^[[:space:]]*//')
            if [ -z "$SCHEME" ]; then
              echo "❌ Could not detect a scheme from project."
              exit 1
            fi
            echo "Using scheme: $SCHEME"
            xcode-project build-ipa \
              --project "$PROJECT" \
              --scheme "$SCHEME" \
              --archive-flags "-destination 'generic/platform=iOS'"
          else
            echo "❌ No .xcworkspace or .xcodeproj found anywhere under $CM_BUILD_DIR"
            echo "Recursive listing to help debug:"
            ls -R "$CM_BUILD_DIR"
            exit 1
          fi

    # ---- Automatic TestFlight upload ----
    publishing:
      app_store_connect:
        auth: integration

        # TestFlight
        submit_to_testflight: true
        expire_build_submitted_for_review: true

        # Optional: only if you have groups created in App Store Connect
        # beta_groups:
        #   - Internal Testers

        # App Store (keep off for now)
        submit_to_app_store: false
