workflows:
  ios_poc:
    name: iOS TryggSamtal PoC
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "TryggSamtal.xcodeproj"
        XCODE_SCHEME: "TryggSamtal"
        BUNDLE_ID: "com.yourname.tryggsamtal"   # byt till samma som i project.yml
        APP_STORE_CONNECT_ISSUER_ID: "47854e61-50b6-4773-9d7d-da77933ae014"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "4R3W9H9Z3B"
        APP_STORE_CONNECT_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgE41H7EQhnEdaX/GIAft2+tchU/FnOxSCy6L1hePL6OGgCgYIKoZIzj0DAQehRANCAAQRglvMmcO5TCDSEp+IL0q3ElpLQEIS6FM5E5SM1bgErNxKkSu3yfP98KrwI6SnskxUaWd4h/ykTtQOueBb4TOF-----END PRIVATE KEY-----"


    scripts:
      - name: Install tools
        script: |
          brew update || true
          brew install xcodegen || true

      - name: Fetch whisper.cpp
        script: |
          mkdir -p vendor
          if [ ! -d vendor/whisper.cpp ]; then
            git clone --depth 1 https://github.com/ggerganov/whisper.cpp.git vendor/whisper.cpp
          fi

      - name: Add Whisper model
        script: |
          mkdir -p Resources/Models
          if [ ! -f Resources/Models/ggml-base.bin ]; then
            curl -L -o Resources/Models/ggml-base.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin
          fi

      - name: Generate Xcode project via XcodeGen
        script: |
          xcodegen generate
          ls -la

      - name: Sanity check App Store Connect env vars
        script: |
          if [ -z "$APP_STORE_CONNECT_ISSUER_ID" ]; then
            echo "MISS: APP_STORE_CONNECT_ISSUER_ID is empty"; exit 1
          else
            echo "OK: APP_STORE_CONNECT_ISSUER_ID present"
          fi
          if [ -z "$APP_STORE_CONNECT_KEY_IDENTIFIER" ]; then
            echo "MISS: APP_STORE_CONNECT_KEY_IDENTIFIER is empty"; exit 1
          else
            echo "OK: APP_STORE_CONNECT_KEY_IDENTIFIER present"
          fi
          if [ -z "$APP_STORE_CONNECT_PRIVATE_KEY" ]; then
            echo "MISS: APP_STORE_CONNECT_PRIVATE_KEY is empty"; exit 1
          else
            echo "OK: APP_STORE_CONNECT_PRIVATE_KEY present"
          fi


      - name: Build .ipa
        script: |
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - $XCODE_PROJECT

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true

