workflows:
  ios_poc:
    name: "iOS TryggSamtal PoC"
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: "com.yourname.tryggsamtal"
        TEAM_ID: "93397B64RG"
        XCODE_PROJECT: "TryggSamtal.xcodeproj"
        XCODE_SCHEME: "TryggSamtal"
        IPA_NAME: "TryggSamtal"
        CODESIGN_ID: "Apple Development: Dane Benjamen"
        PROVISIONING_PROFILE_NAME: "TryggsamtalDev"
        PROFILE_PATH: "profiles/TryggsamtalDev.mobileprovision"
      groups:
        - admin

    scripts:
      - name: Install tools
        script: |
          brew update || true
          brew install xcodegen xcbeautify || true

      - name: Generate Xcode project via XcodeGen
        script: |
          echo "PWD:" && pwd
          ls -la
          if [ -f project.yml ]; then
            xcodegen generate
          else
            echo "❌ Missing project.yml file"; exit 1
          fi

      - name: Diagnose p12 env payload
        script: |
          set -e
          echo ">>> Validating CERT_P12_B64 and CERT_P12_PASSWORD..."
          if [ -z "$CERT_P12_B64" ] || [ -z "$CERT_P12_PASSWORD" ]; then
            echo "❌ Missing CERT_P12_B64 or CERT_P12_PASSWORD"; exit 1
          fi
          echo "$CERT_P12_B64" | base64 --decode > check.p12
          echo ">>> File type:"
          file check.p12 || true
          echo ">>> Trying to open .p12 with provided password..."
          if ! (openssl pkcs12 -in check.p12 -nokeys -passin pass:"$CERT_P12_PASSWORD" -info -clcerts >/dev/null 2>&1); then
            echo "❌ OpenSSL could not read the PKCS#12 with the given password (wrong password or corrupted p12)"
            exit 1
          fi
          echo "✅ OpenSSL verified the PKCS#12 successfully"

      - name: Inject Apple Development .p12 from env
        script: |
          echo ">>> Injecting Apple Development certificate..."
          echo "$CERT_P12_B64" | base64 --decode > ios_dev.p12
          security create-keychain -p "" build.keychain
          security import ios_dev.p12 -k ~/Library/Keychains/build.keychain -P "$CERT_P12_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/Library/Keychains/build.keychain
          echo "✅ Certificate imported into keychain successfully"

      - name: Install provisioning profile
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp "$PROFILE_PATH" ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "✅ Provisioning profile copied to correct folder"

      - name: Build .ipa (archive + export)
        script: |
          set -e
          echo ">>> Clean"
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" | xcbeautify
          echo ">>> Show key build settings (pre-archive)"
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -showBuildSettings | grep -E 'CODE_SIGN|TEAM|PRODUCT_BUNDLE_IDENTIFIER'
          echo ">>> Archive"
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/ios/TryggSamtal.xcarchive \
            CODE_SIGN_IDENTITY="$CODESIGN_ID" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_NAME" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" | xcbeautify

          echo ">>> Exporting IPA"
          mkdir -p build/ios/ipa
          xcodebuild -exportArchive \
            -archivePath build/ios/TryggSamtal.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist <(cat <<EOF
          {
            "method": "development",
            "teamID": "$TEAM_ID",
            "signingStyle": "manual",
            "provisioningProfiles": { "$BUNDLE_ID": "$PROVISIONING_PROFILE_NAME" },
            "compileBitcode": false
          }
          EOF
          )
          echo "✅ IPA export done"
          ls -R build/ios/ipa || true

      - name: Upload to TestFlight
        script: |
          echo ">>> Uploading to TestFlight..."
          app-store-connect publish \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --path build/ios/ipa/*.ipa \
            --testflight \
            --whats-new "Initial TryggSamtal PoC build"

    artifacts:
      - build/ios/ipa/*.ipa
