workflows:
  ios_release:
    name: "TryggSamtal iOS Release"

    # App Store Connect integration (API key) – already created in Codemagic as "codemagic"
    integrations:
      app_store_connect: codemagic

    environment:
      xcode: latest

      # iOS code signing configuration for codemagic.yaml workflows
      # These reference names MUST match what you configure under:
      # Team settings → codemagic.yaml settings → Code signing identities
      ios_signing:
        certificates:
          # Reference name of your uploaded iOS Distribution .p12
          - tryggsamtal_dist_cert
        provisioning_profiles:
          # Reference name of your uploaded App Store distribution .mobileprovision
          - tryggsamtal_dist_profile

    scripts:
      # 1) Generate Xcode project from project.yml using XcodeGen
      - name: Generate Xcode project
        script: |
          set -e
          cd "$CM_BUILD_DIR"

          echo "Top-level contents:"
          ls
          echo

          if [ ! -f "project.yml" ]; then
            echo "❌ project.yml not found in $CM_BUILD_DIR"
            exit 1
          fi

          if ! command -v xcodegen >/dev/null 2>&1; then
            echo "Installing XcodeGen via Homebrew..."
            brew install xcodegen
          fi

          echo "Generating Xcode project with XcodeGen..."
          xcodegen generate

          echo "Contents after xcodegen:"
          ls
          echo

      # 2) Apply signing (cert + provisioning profile) to the Xcode project
      #    This will also generate $HOME/export_options.plist
      - name: Set up code signing on Xcode project
        script: |
          set -e
          cd "$CM_BUILD_DIR"

          PROJECT="$CM_BUILD_DIR/TryggSamtal.xcodeproj"

          if [ ! -d "$PROJECT" ]; then
            echo "❌ Project not found at $PROJECT"
            ls
            exit 1
          fi

          echo "Applying provisioning profiles with xcode-project use-profiles..."
          xcode-project use-profiles \
            --project "$PROJECT"

          echo "Checking for export_options.plist generated by use-profiles..."
          if [ ! -f "$HOME/export_options.plist" ]; then
            echo "❌ export_options.plist not found at \$HOME/export_options.plist"
            ls "$HOME"
            exit 1
          fi

      # 3) Build IPA using the generated export_options.plist
      - name: Build IPA
        script: |
          set -e
          cd "$CM_BUILD_DIR"

          PROJECT="$CM_BUILD_DIR/TryggSamtal.xcodeproj"
          SCHEME="TryggSamtal"
          EXPORT_PLIST="$HOME/export_options.plist"

          if [ ! -d "$PROJECT" ]; then
            echo "❌ Project not found at $PROJECT"
            ls
            exit 1
          fi

          if [ ! -f "$EXPORT_PLIST" ]; then
            echo "❌ export_options.plist not found at $EXPORT_PLIST"
            ls "$HOME"
            exit 1
          fi

          echo "Using project: $PROJECT"
          echo "Using scheme: $SCHEME"
          echo "Using export options: $EXPORT_PLIST"

          xcode-project build-ipa \
            --project "$PROJECT" \
            --scheme "$SCHEME" \
            --export-options-plist "$EXPORT_PLIST"

    # 4) Publish the built IPA to App Store Connect / TestFlight
    publishing:
      app_store_connect:
        auth: integration

        # TestFlight
        submit_to_testflight: true
        expire_build_submitted_for_review: true

        # Optional: add existing TestFlight beta group names if you have them
        # beta_groups:
        #   - Internal Testers

        # Keep App Store submission off for now
        submit_to_app_store: false
