workflows:
  ios_poc:
    name: "iOS TryggSamtal PoC"
    environment:
      xcode: latest
      groups:
        - admin
      vars:
        BUNDLE_ID: "com.yourname.tryggsamtal"
        TEAM_ID: "93397B64RG"
        XCODE_PROJECT: "TryggSamtal.xcodeproj"
        XCODE_SCHEME: "TryggSamtal"
        IPA_NAME: "TryggSamtal"
        CODESIGN_ID: "Apple Development"
        PROFILE_PATH: "profiles/TryggSamtalDev.mobileprovision"
        KEYCHAIN_PATH: "$HOME/Library/Keychains/build.keychain-db"

    scripts:
      - name: Install tools
        script: |
          brew update || true
          brew install xcodegen xcbeautify openssl || true

      - name: Generate Xcode project via XcodeGen
        script: |
          echo "PWD:" && pwd
          ls -la
          if [ -f project.yml ]; then
            xcodegen generate
          else
            echo "❌ Missing project.yml file"; exit 1
          fi
          test -f "TryggSamtal.xcodeproj/project.pbxproj" || { echo "❌ XcodeGen failed"; exit 1; }

      - name: Diagnose p12 env payload
        script: |
          set -e
          echo ">>> Validating CERT_P12_B64 and CERT_P12_PASSWORD..."
          if [ -z "$CERT_P12_B64" ] || [ -z "$CERT_P12_PASSWORD" ]; then
            echo "❌ Missing CERT_P12_B64 or CERT_P12_PASSWORD"; exit 1
          fi
          echo "$CERT_P12_B64" | base64 --decode > check.p12
          if ! (openssl pkcs12 -in check.p12 -nokeys -passin pass:"$CERT_P12_PASSWORD" -info -clcerts >/dev/null 2>&1); then
            echo "❌ Wrong password or corrupted p12"; exit 1
          fi
          echo "✅ OpenSSL verified the PKCS#12 successfully"

      - name: Create and configure keychain
        script: |
          set -e
          echo ">>> Creating keychain at $KEYCHAIN_PATH"
          security create-keychain -p "" "$KEYCHAIN_PATH"
          security list-keychains -d user -s "$KEYCHAIN_PATH"
          security default-keychain -s "$KEYCHAIN_PATH"
          security unlock-keychain -p "" "$KEYCHAIN_PATH"
          echo "✅ Keychain created & set as default"

      - name: Inject Apple Development .p12 into keychain (robust)
        script: |
          set -e
          echo ">>> Importing Apple Development certificate..."
          echo "$CERT_P12_B64" | base64 --decode > ios_dev.p12
          if security import ios_dev.p12 -k "$KEYCHAIN_PATH" -P "$CERT_P12_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security; then
            echo "✅ Direct security import succeeded"
          else
            echo "⚠️ Direct import failed; extracting cert+key PEM and importing separately..."
            openssl pkcs12 -in ios_dev.p12 -passin pass:"$CERT_P12_PASSWORD" -nodes -clcerts -out extracted.pem
            awk 'BEGIN{p=0} /BEGIN CERTIFICATE/{p=1} p{print} /END CERTIFICATE/{p=0}' extracted.pem > dev_cert.pem
            awk 'BEGIN{p=0} /BEGIN PRIVATE KEY/{p=1} p{print} /END PRIVATE KEY/{p=0}' extracted.pem > dev_key.pem
            security import dev_cert.pem -k "$KEYCHAIN_PATH" -T /usr/bin/codesign -T /usr/bin/security
            security import dev_key.pem -k "$KEYCHAIN_PATH" -P "" -A -t private -f pem
            rm -f extracted.pem dev_cert.pem dev_key.pem
            echo "✅ Imported certificate and private key separately"
          fi
          security set-key-partition-list -S apple-tool:,apple: -s -k "" "$KEYCHAIN_PATH"
          echo "✅ Key partition list set"

      - name: Install provisioning profile (extract UUID)
        script: |
          set -e
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          if [ ! -f "$PROFILE_PATH" ]; then
            echo "❌ Provisioning profile not found at $PROFILE_PATH"; exit 1
          fi
          PLIST=$(security cms -D -i "$PROFILE_PATH")
          UUID=$(echo "$PLIST" | plutil -extract UUID raw -)
          cp "$PROFILE_PATH" "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.mobileprovision"
          echo "PROVISIONING_PROFILE_UUID=$UUID" >> $CM_ENV
          echo "✅ Installed profile $UUID"

      - name: Build .ipa (archive + export)
        script: |
          set -e
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -sdk iphoneos -destination 'generic/platform=iOS' | xcbeautify
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath "build/ios/${IPA_NAME}.xcarchive" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="${CODESIGN_ID}" \
            DEVELOPMENT_TEAM="${TEAM_ID}" \
            PRODUCT_BUNDLE_IDENTIFIER="${BUNDLE_ID}" \
            PROVISIONING_PROFILE_SPECIFIER="${PROVISIONING_PROFILE_UUID}" \
            | xcbeautify
          cat > export_options.plist <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>development</string>
            <key>teamID</key><string>${TEAM_ID}</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict><key>${BUNDLE_ID}</key><string>${PROVISIONING_PROFILE_UUID}</string></dict>
            <key>compileBitcode</key><false/>
          </dict></plist>
          PLIST
          xcodebuild -exportArchive \
            -archivePath "build/ios/${IPA_NAME}.xcarchive" \
            -exportOptionsPlist export_options.plist \
            -exportPath build/ios/ipa | xcbeautify

      - name: "Preflight: verify App Store Connect API access"
        script: |
          set -e
          printf "%s" "$APP_STORE_CONNECT_PRIVATE_KEY" > appstore_key.p8
          echo "Key header: $(head -n 1 appstore_key.p8)"
          echo "Key footer: $(tail -n 1 appstore_key.p8)"
          openssl pkey -in appstore_key.p8 -noout || { echo "❌ Invalid private key format"; exit 1; }

      - name: Upload to TestFlight
        script: |
          set -e
          IPA="$(ls build/ios/ipa/*.ipa 2>/dev/null | head -n 1)"
          [ -n "$IPA" ] || { echo "❌ No IPA found to upload"; exit 1; }
          echo ">>> Uploading to TestFlight via altool"
          xcrun altool --upload-app \
            --file "$IPA" \
            --type ios \
            --apiKey "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --apiIssuer "$APP_STORE_CONNECT_ISSUER_ID" \
            --output-format json | tee altool_upload.json
          echo "✅ Upload command executed"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/*.xcarchive
      - export_options.plist
      - altool_upload.json
