workflows:
  ios_poc:
    name: iOS TryggSamtal PoC
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "TryggSamtal.xcodeproj"
        XCODE_SCHEME: "TryggSamtal"
        BUNDLE_ID: "com.yourname.tryggsamtal"
        TEAM_ID: "93397B64RG"
        PROVISIONING_PROFILE_PATH: "profiles/Tryggsamtal-Dev.mobileprovision"
        CODESIGN_ID: "Apple Development"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "<DIN_KEY_ID>"
        APP_STORE_CONNECT_ISSUER_ID: "<DIN_ISSUER_ID>"
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...) # Din API key in secret storage

    scripts:
      - name: Install tools
        script: |
          brew update || true
          brew install xcodegen || true
          brew install xcbeautify || true

      - name: Generate Xcode project via XcodeGen
        script: |
          echo "PWD:" && pwd
          echo "List before:" && ls -la
          xcodegen generate --spec project.yml
          echo "List after:" && ls -la
          if [ ! -f "TryggSamtal.xcodeproj/project.pbxproj" ]; then
            echo "ERROR: XcodeGen failed to create TryggSamtal.xcodeproj"
            exit 1
          fi

      - name: Install local provisioning profile
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp "$PROVISIONING_PROFILE_PATH" ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "Installed provisioning profile:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Set up keychain and add uploaded certificates
        script: |
          keychain initialize
          keychain add-certificates
          echo ">>> iOS certificates:"
          ls -la /Users/builder/Library/MobileDevice/Certificates || true

      - name: Debug: list code signing identities
        script: |
          echo ">>> Listing uploaded .p12 files"
          ls -la /Users/builder/Library/MobileDevice/Certificates || true

          echo ">>> Listing identities in Codemagic keychain"
          security find-identity -v -p codesigning ~/Library/codemagic-cli-tools/keychains/*.keychain-db || true

          echo ">>> Listing system/login keychains"
          security find-identity -v -p codesigning /Library/Keychains/System.keychain || true
          security find-identity -v -p codesigning ~/Library/Keychains/login.keychain-db || true

          echo ">>> Expecting to find: $CODESIGN_ID"
          if ! security find-identity -v -p codesigning ~/Library/codemagic-cli-tools/keychains/*.keychain-db | grep -F "$CODESIGN_ID" >/dev/null; then
            echo "ERROR: Codesign identity '$CODESIGN_ID' not found!"
            echo "Upload correct Apple Development .p12 under Code signing identities in Codemagic."
            exit 1
          fi

      - name: Build .ipa (archive + export)
        script: |
          mkdir -p build/ios
          xcodebuild clean archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/ios/TryggSamtal.xcarchive \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="$CODESIGN_ID" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="Tryggsamtal-Dev" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            | xcbeautify

          xcodebuild -exportArchive \
            -archivePath build/ios/TryggSamtal.xcarchive \
            -exportOptionsPlist <(cat <<EOF
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
              <key>method</key><string>development</string>
              <key>teamID</key><string>${TEAM_ID}</string>
              <key>signingStyle</key><string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                <key>${BUNDLE_ID}</key><string>Tryggsamtal-Dev</string>
              </dict>
            </dict>
            </plist>
            EOF) \
            -exportPath build/ios/ipa \
            | xcbeautify

      - name: Upload to TestFlight
        script: |
          app-store-connect publish \
            --path "build/ios/ipa/TryggSamtal.ipa" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/TryggSamtal.xcarchive
