workflows:
  ios_poc:
    name: "iOS TryggSamtal PoC"
    environment:
      xcode: latest
      groups:
        - admin
      vars:
        BUNDLE_ID: "com.yourname.tryggsamtal"
        TEAM_ID: "93397B64RG"
        XCODE_PROJECT: "TryggSamtal.xcodeproj"
        XCODE_SCHEME: "TryggSamtal"
        IPA_NAME: "TryggSamtal"
        CODESIGN_ID: "Apple Development"
        PROFILE_PATH: "profiles/TryggsamtalDev.mobileprovision"
        KEYCHAIN_PATH: "$HOME/Library/Keychains/build.keychain-db"

    scripts:
      - name: Install tools
        script: |
          brew update || true
          brew install xcodegen xcbeautify || true

      - name: Generate Xcode project via XcodeGen
        script: |
          echo "PWD:" && pwd
          ls -la
          if [ -f project.yml ]; then
            xcodegen generate
          else
            echo "❌ Missing project.yml file"; exit 1
          fi
          test -f "TryggSamtal.xcodeproj/project.pbxproj" || { echo "❌ XcodeGen failed"; exit 1; }

      - name: Diagnose p12 env payload
        script: |
          set -e
          echo ">>> Validating CERT_P12_B64 and CERT_P12_PASSWORD..."
          if [ -z "$CERT_P12_B64" ] || [ -z "$CERT_P12_PASSWORD" ]; then
            echo "❌ Missing CERT_P12_B64 or CERT_P12_PASSWORD"; exit 1
          fi
          echo "$CERT_P12_B64" | base64 --decode > check.p12
          echo ">>> File type:" && file check.p12 || true
          if ! (openssl pkcs12 -in check.p12 -nokeys -passin pass:"$CERT_P12_PASSWORD" -info -clcerts >/dev/null 2>&1); then
            echo "❌ OpenSSL could not read the PKCS#12 with the given password"
            exit 1
          fi
          echo "✅ OpenSSL verified the PKCS#12 successfully"

      - name: Create and configure keychain (no partition-list yet)
        script: |
          set -e
          echo ">>> Creating keychain at $KEYCHAIN_PATH"
          security create-keychain -p "" "$KEYCHAIN_PATH"
          security list-keychains -d user -s "$KEYCHAIN_PATH"
          security default-keychain -s "$KEYCHAIN_PATH"
          security unlock-keychain -p "" "$KEYCHAIN_PATH"
          echo "✅ Keychain created & set as default"

      - name: Inject Apple Development .p12 into keychain (robust, no heredocs)
        script: |
          set -e
          echo ">>> Importing Apple Development certificate..."
          echo "$CERT_P12_B64" | base64 --decode > ios_dev.p12

          if security import ios_dev.p12 -k "$KEYCHAIN_PATH" -P "$CERT_P12_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security; then
            echo "✅ Direct security import succeeded"
          else
            echo "⚠️ Direct import failed; extracting cert+key PEM and importing separately..."
            openssl pkcs12 -in ios_dev.p12 -passin pass:"$CERT_P12_PASSWORD" -nodes -clcerts -out extracted.pem
            awk 'BEGIN{p=0} /BEGIN CERTIFICATE/{p=1} p{print} /END CERTIFICATE/{p=0}' extracted.pem > dev_cert.pem
            awk 'BEGIN{p=0} /BEGIN PRIVATE KEY/{p=1} p{print} /END PRIVATE KEY/{p=0}' extracted.pem > dev_key.pem
            security import dev_cert.pem -k "$KEYCHAIN_PATH" -T /usr/bin/codesign -T /usr/bin/security
            security import dev_key.pem -k "$KEYCHAIN_PATH" -P "" -A -t private -f pem
            rm -f extracted.pem dev_cert.pem dev_key.pem
            echo "✅ Imported certificate and private key separately"
          fi

          security find-identity -v -p codesigning "$KEYCHAIN_PATH" || true
          security set-key-partition-list -S apple-tool:,apple: -s -k "" "$KEYCHAIN_PATH"
          echo "✅ Key partition list set"

      - name: Install provisioning profile (extract UUID)
        script: |
          set -e
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          if [ ! -f "$PROFILE_PATH" ]; then
            echo "❌ Provisioning profile not found at $PROFILE_PATH"; exit 1
          fi
          echo "Found profile: $PROFILE_PATH"
          PLIST=$(security cms -D -i "$PROFILE_PATH")
          UUID=$(echo "$PLIST" | plutil -extract UUID raw -)
          NAME=$(echo "$PLIST" | plutil -extract Name raw - 2>/dev/null || true)
          echo "Profile Name: ${NAME:-<unknown>}"
          echo "Profile UUID: $UUID"
          cp "$PROFILE_PATH" "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.mobileprovision"
          echo "PROVISIONING_PROFILE_UUID=$UUID" >> $CM_ENV

      - name: Build .ipa (archive + export)
        script: |
          set -e
          echo ">>> Clean"
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -sdk iphoneos -destination 'generic/platform=iOS' | xcbeautify

          echo ">>> Archive"
          set -o pipefail
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath "build/ios/${IPA_NAME}.xcarchive" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="${CODESIGN_ID}" \
            DEVELOPMENT_TEAM="${TEAM_ID}" \
            PRODUCT_BUNDLE_IDENTIFIER="${BUNDLE_ID}" \
            PROVISIONING_PROFILE_SPECIFIER="${PROVISIONING_PROFILE_UUID}" \
            | tee xcodebuild_archive.log | xcbeautify

          echo ">>> Write export options to file"
          cat > export_options.plist <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>development</string>
            <key>teamID</key><string>${TEAM_ID}</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${BUNDLE_ID}</key><string>${PROVISIONING_PROFILE_UUID}</string>
            </dict>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          PLIST

          echo ">>> Export IPA"
          xcodebuild -exportArchive \
            -archivePath "build/ios/${IPA_NAME}.xcarchive" \
            -exportOptionsPlist export_options.plist \
            -exportPath build/ios/ipa \
            | xcbeautify

          echo "IPA(s) created:"
          ls -la build/ios/ipa || true

      - name: Sanity check App Store Connect env vars
        script: |
          miss=0
          for v in APP_STORE_CONNECT_ISSUER_ID APP_STORE_CONNECT_KEY_IDENTIFIER APP_STORE_CONNECT_PRIVATE_KEY; do
            if [ -z "${!v}" ]; then echo "MISS: $v is empty"; miss=1; else echo "OK: $v present"; fi
          done
          [ $miss -eq 0 ] || { echo "❌ Fix missing env vars in Codemagic → Environment variables (group 'admin')"; exit 1; }

      - name: Upload to TestFlight (verbose + auto-log dump)
        script: |
          set -e
          IPA="$(ls build/ios/ipa/*.ipa 2>/dev/null | head -n 1)"
          if [ -z "$IPA" ]; then echo "❌ No IPA found to upload"; exit 1; fi

          printf "%s\n" "$APP_STORE_CONNECT_PRIVATE_KEY" > appstore_key.p8
          chmod 600 appstore_key.p8
          echo "Key header: $(head -n 1 appstore_key.p8)"
          echo "Key footer: $(tail -n 1 appstore_key.p8)"

          echo ">>> Uploading to TestFlight (verbose)"
          set +e
          app-store-connect publish \
            --path "$IPA" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key appstore_key.p8 \
            --platform IOS \
            --testflight \
            --verbose
          EXIT=$?
          set -e

          if [ $EXIT -ne 0 ]; then
            echo "⚠️ publish exited with $EXIT — dumping Codemagic log if present…"
            FOUND_LOG="$(find /var/folders -type f -name 'codemagic-*.log' 2>/dev/null | tail -n 1 || true)"
            if [ -n "$FOUND_LOG" ]; then
              echo "------ BEGIN app-store-connect LOG ($FOUND_LOG) ------"
              tail -n 500 "$FOUND_LOG" || true
              echo "------- END app-store-connect LOG -------"
            fi
            exit $EXIT
          fi

          echo "✅ Upload queued."

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/*.xcarchive
      - export_options.plist
