name: Deploy iOS to TestFlight

on:
  workflow_dispatch: # Allows manual trigger
  # Or on push: 
  # push:
  #   branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Compatible with Fastlane
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build and Deploy to TestFlight
        run: bundle exec fastlane beta
        working-directory: ./ # For Flutter, change to ./ if Fastfile is at root; or ./ios if native
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
