name: TryggSamtal
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "16.0"

settings:
  base:
    # MÅSTE vara exakt din bundle id (samma som i provisioning-profilen)
    PRODUCT_BUNDLE_IDENTIFIER: com.yourname.tryggsamtal
    # håll team/provisioning här också för att undvika konflikt
    DEVELOPMENT_TEAM: 93397B64RG
    CODE_SIGN_STYLE: Manual
    SWIFT_VERSION: 5.9
    INFOPLIST_FILE: Resources/Info.plist

targets:
  TryggSamtal:
    type: application
    platform: iOS
    sources:
      - path: UI
      - path: Audio
      - path: STT
      - path: STTRuntime
      - path: Detection
      - path: Services
      - path: Resources
    settings:
      base:
        # exakt profilnamn (”Name”) från Apple/Codemagic
        PROVISIONING_PROFILE_SPECIFIER: Tryggsamtal-Dev
        PRODUCT_NAME: TryggSamtal
        TARGETED_DEVICE_FAMILY: "1"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        OTHER_CFLAGS: $(inherited)
        OTHER_LDFLAGS: $(inherited)
        ENABLE_BITCODE: NO
    scheme:
      name: TryggSamtal
