name: TryggSamtal
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "16.0"

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.yourname.tryggsamtal   # <-- BYT (samma som i codemagic.yaml)
    DEVELOPMENT_TEAM: 93397B64RG                          # <-- BYT
    SWIFT_VERSION: 5.9
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: Apple Development
    INFOPLIST_FILE: Resources/Info.plist

targets:
  TryggSamtal:
    type: application
    platform: iOS
    sources:
      - path: UI
      - path: Audio
      - path: STT
      - path: STTRuntime
      - path: Detection
      - path: Services
      - path: Resources
    settings:
      base:
        PRODUCT_NAME: TryggSamtal
        TARGETED_DEVICE_FAMILY: "1"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        OTHER_CFLAGS: $(inherited)
        OTHER_LDFLAGS: $(inherited)
        ENABLE_BITCODE: NO
    scheme:
      name: TryggSamtal
